background = rgba(0, 0, 0, 0.74)
rounding_large = 0
rounding_small = 0
font_family = MesloLGLDZ Nerd Font Propo
accent = rgb(254, 252, 255)
accent secondary = rgb(254, 252, 255)
base = rgb(0, 0, 0)
text = rgb(254, 252, 255)
